### ISSUE TITLE
after fixing folder names, we should restructure things

### ISSUE THREAD

**Issue by dcuartielles** [arduino/livecast#2]
We should have a folder structure as follows:

- episode name / 
  episode name /sketchname/
  episode name /sketchname/sketch.ino
  episode name /sketchname/extra.h
  episode name /img/
  episode name /img/fritzing.png
  episode name /processing program or other software
  episode name /Readme.md

This will help people navigating things in an easier way.

**Comment by per1234** [comment]
The reason I moved the readme and image files to the sketch folder is that Arduino Web Editor displays those files as tabs along with the sketch, which it will not do with the folder structure proposed here. If it weren't for that, I'd also prefer the readme file to be in the episode folder, since that makes that file more visible to someone browsing the repository.
![clipboard01](https://user-images.githubusercontent.com/8572152/49146833-d7e75880-f2b7-11e8-9964-9f40a3d38a5f.png)

**Comment by dcuartielles** [comment]
Hej @per1234 it makes sense ... I think we could have the schematic in the same place as the code and other images under img folder.

Want to make the honors?
